wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.33.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694692082.428649
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      3:
      - 13
      - 23
      4: 3.8.18
      5: 0.15.10
      6: 4.33.1
      8:
      - 5
